# Generated by Django 5.2.7 on 2025-10-28 22:41

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    'short_description',
                    models.CharField(blank=True, default='', max_length=500),
                ),
                ('description', models.TextField(blank=True, default='')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('idea', 'Idea'),
                            ('mvp', 'MVP'),
                            ('fundraising', 'Fundraising'),
                            ('closed', 'Closed'),
                        ],
                        db_index=True,
                        default='idea',
                        max_length=20,
                    ),
                ),
                (
                    'target_amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.01'))
                        ],
                    ),
                ),
                (
                    'raised_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0'))
                        ],
                    ),
                ),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                (
                    'tags',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    'visibility',
                    models.CharField(
                        choices=[
                            ('public', 'Public'),
                            ('private', 'Private'),
                            ('unlisted', 'Unlisted'),
                        ],
                        default='public',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'deleted_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='deleted_projects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'startup',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects',
                        to='startups.startupprofile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('file', models.FileField(upload_to='project_attachments/%Y/%m')),
                ('type', models.CharField(max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attachments',
                        to='projects.project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project Attachment',
                'verbose_name_plural': 'Project Attachments',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAudit',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changes', models.JSONField()),
                ('user_agent', models.TextField(blank=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_logs',
                        to='projects.project',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project Audit Log',
                'verbose_name_plural': 'Project Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['startup', 'status'], name='projects_pr_startup_2b2945_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['created_at'], name='projects_pr_created_6b02e3_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_deleted'], name='projects_pr_is_dele_b32018_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(
                fields=['project', 'timestamp'], name='projects_pr_project_e8b5b1_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(
                fields=['user', 'timestamp'], name='projects_pr_user_id_a7e7a8_idx'
            ),
        ),
    ]
