# Generated by Django 5.2.7 on 2025-11-10 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_projects',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='startup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='projects',
                to='startups.startupprofile',
            ),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attachments',
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audit_logs',
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['startup', 'status'], name='projects_pr_startup_2b2945_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['created_at'], name='projects_pr_created_6b02e3_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_deleted'], name='projects_pr_is_dele_b32018_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(
                fields=['project', 'timestamp'], name='projects_pr_project_e8b5b1_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(
                fields=['user', 'timestamp'], name='projects_pr_user_id_a7e7a8_idx'
            ),
        ),
    ]
