# Generated by Django 5.2.5 on 2025-10-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile'),
        ),
    ]
