# Generated by Django 5.2.7 on 2025-10-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['startup', 'status'], name='projects_pr_startup_2b2945_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(fields=['project', 'timestamp'], name='projects_pr_project_e8b5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(fields=['user', 'timestamp'], name='projects_pr_user_id_a7e7a8_idx'),
        ),
    ]
