# Generated by Django 5.2.7 on 2025-10-21 18:44

from decimal import Decimal

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_short_description_project_short_desc_and_more'),
        ('startups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.FileField(upload_to='project_attachments/%Y/%m')),
                ('type', models.CharField(max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Attachment',
                'verbose_name_plural': 'Project Attachments',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAudit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changes', models.JSONField()),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Audit Log',
                'verbose_name_plural': 'Project Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='raised_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='projects',
                to='startups.startupprofile',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ('idea', 'Idea'),
                    ('mvp', 'MVP'),
                    ('fundraising', 'Fundraising'),
                    ('closed', 'Closed'),
                ],
                db_index=True,
                default='idea',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('public', 'Public'),
                    ('private', 'Private'),
                    ('unlisted', 'Unlisted'),
                ],
                default='public',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['startup', 'status'], name='projects_pr_startup_2b2945_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['created_at'], name='projects_pr_created_6b02e3_idx'
            ),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attachments',
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audit_logs',
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(
                fields=['project', '-timestamp'], name='projects_pr_project_0e7a37_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectaudit',
            index=models.Index(
                fields=['user', '-timestamp'], name='projects_pr_user_id_cdadf2_idx'
            ),
        ),
    ]
