# Generated by Django 5.2.7 on 2025-10-21 19:29
import uuid

from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectAttachment = apps.get_model("projects", "ProjectAttachment")
    ProjectAudit = apps.get_model("projects", "ProjectAudit")

    for obj in Project.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])

    for obj in ProjectAttachment.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])

    for obj in ProjectAudit.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_projectattachment_projectaudit_alter_project_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="projectattachment",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="projectaudit",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="projectattachment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="projectaudit",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
