# Generated by Django 5.2.7 on 2025-11-02 20:32

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_deleted_at_project_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_overfunding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=django_fsm.FSMField(
                choices=[
                    ('idea', 'Idea'),
                    ('mvp', 'MVP'),
                    ('fundraising', 'Fundraising'),
                    ('funded', 'Funded'),
                    ('closed', 'Closed'),
                ],
                db_index=True,
                default='idea',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('public', 'Public'),
                    ('private', 'Private'),
                    ('unlisted', 'Unlisted'),
                ],
                default='private',
                max_length=20,
            ),
        ),
    ]
