# Generated by Django 5.2.7 on 2025-10-24 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_uuid_fields_if_exist(apps, schema_editor):
    """Safely remove UUID fields if they exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        # Get columns for each table
        tables_and_columns = {
            'projects_project': ['uuid'],
            'projects_projectattachment': ['project_uuid', 'uuid'],
            'projects_projectaudit': ['project_uuid', 'uuid'],
        }

        for table, columns in tables_and_columns.items():
            for column in columns:
                # Check if column exists
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name=%s AND column_name=%s
                """, [table, column])

                if cursor.fetchone():
                    # Column exists, drop it
                    cursor.execute(f'ALTER TABLE {table} DROP COLUMN {column}')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_projectaudit_projects_pr_project_0e7a37_idx_and_more'),
        ('startups', '0003_alter_savedstartup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='projectattachment',
            name='project_uuid',
        ),
        migrations.RemoveField(
            model_name='projectattachment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='projectaudit',
            name='project_uuid',
        ),
        migrations.RemoveField(
            model_name='projectaudit',
            name='uuid',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_deleted'], name='projects_pr_is_dele_b32018_idx'),
        ),
    ]
