# Generated by Django 5.2.7 on 2025-10-28 22:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                (
                    'founded_year',
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                    ),
                ),
                ('team_size', models.IntegerField(blank=True, default=1, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                (
                    'postal_code',
                    models.CharField(blank=True, default='', max_length=20),
                ),
                (
                    'logo',
                    models.ImageField(
                        blank=True, null=True, upload_to='startup_logos/%Y/%m/'
                    ),
                ),
                ('partners_brands', models.TextField(blank=True, default='')),
                (
                    'audit_status',
                    models.CharField(blank=True, default='', max_length=100),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='startup_profiles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Startup Profile',
                'verbose_name_plural': 'Startup Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedStartup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'investor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saved_startups',
                        to='investors.investorprofile',
                    ),
                ),
                (
                    'startup',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saved_by_investors',
                        to='startups.startupprofile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Saved Startup',
                'verbose_name_plural': 'Saved Startups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['user'], name='startups_st_user_id_0e7c16_idx'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(
                fields=['company_name'], name='startups_st_company_7bb0ef_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(
                fields=['-created_at'], name='startups_st_created_dab4a1_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='savedstartup',
            unique_together={('investor', 'startup')},
        ),
    ]
