# Generated by Django 5.2.7 on 2025-10-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("startups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedstartup',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_investors', to='startups.startupprofile'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['user'], name='startups_st_user_id_0e7c16_idx'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['company_name'], name='startups_st_company_7bb0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['-created_at'], name='startups_st_created_dab4a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedstartup',
            unique_together={('investor', 'startup')},

        ),
    ]
