# Generated by Django 5.2.7 on 2025-10-22 13:43

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.utils.logo_upload_to),
        ),
    ]
