# Generated by Django 5.2.7 on 2025-10-22 13:43

import os
import uuid

from django.db import migrations, models


def logo_upload_to(instance, filename):
    ext = os.path.splitext(filename)[1].lower() or '.png'
    user_id = getattr(getattr(instance, 'user', None), 'id', None)
    user_uuid = str(user_id) if user_id else str(uuid.uuid4())
    filename = f"{user_uuid}{ext}"
    return os.path.join('logos', filename)


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_savedstartup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=logo_upload_to),
        ),
    ]
