# Generated by Django 5.2.7 on 2025-10-22 13:57

from django.db import migrations
import os
import shutil
from django.conf import settings


from apps.common.utils import logo_upload_to

def move_logos(apps, schema_editor):
    """
    Переміщує існуючі логотипи зі старих шляхів (media/startup_logos/ та media/Investor_logos/)
    до нового шляху (media/logos/) з UUID-іменами.
    """
    StartupProfile = apps.get_model('startups', 'StartupProfile')
    InvestorProfile = apps.get_model('investors', 'InvestorProfile')
    
    for profile in StartupProfile.objects.exclude(logo__isnull=True).exclude(logo=''):
        old_logo_name = profile.logo.name
        if old_logo_name.startswith('logos/'):
            continue

        old_path = os.path.join(settings.MEDIA_ROOT, old_logo_name)
        
        if os.path.exists(old_path):
            new_logo_name = logo_upload_to(profile, os.path.basename(old_logo_name))
            new_path = os.path.join(settings.MEDIA_ROOT, new_logo_name)
            
            os.makedirs(os.path.dirname(new_path), exist_ok=True)
            
            shutil.move(old_path, new_path)
            
            profile.logo.name = new_logo_name
            profile.save(update_fields=['logo'])

    for profile in InvestorProfile.objects.exclude(logo__isnull=True).exclude(logo=''):
        old_logo_name = profile.logo.name
        if old_logo_name.startswith('logos/'):
            continue

        old_path = os.path.join(settings.MEDIA_ROOT, old_logo_name)
        
        if os.path.exists(old_path):
            new_logo_name = logo_upload_to(profile, os.path.basename(old_logo_name))
            new_path = os.path.join(settings.MEDIA_ROOT, new_logo_name)
            
            os.makedirs(os.path.dirname(new_path), exist_ok=True)
            shutil.move(old_path, new_path)
            
            profile.logo.name = new_logo_name
            profile.save(update_fields=['logo'])


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startupprofile_logo'),
        ('investors', '0003_alter_investorprofile_logo'),
    ]

    operations = [
        migrations.RunPython(move_logos, reverse_code=migrations.RunPython.noop),
    ]
