# Generated by Django 5.2.7 on 2025-10-31 10:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('startups', '0004_consolidate_logo_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['tags'], name='startups_tags_gin'
            ),
        ),
    ]
