# Generated by Django 5.2.7 on 2025-10-25 13:30

import os
import uuid
from django.db import migrations
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

def consolidate_and_fix_logo_paths(apps, schema_editor):
    """
    Об'єднана міграція для переміщення логотипів.
    - Використовує Django Storage API для безпечної роботи з файлами.
    - Ідемпотентна: обробляє тільки ті файли, які ще не переміщені.
    - Працює як для StartupProfile, так і для InvestorProfile.
    """
    StartupProfile = apps.get_model('startups', 'StartupProfile')
    InvestorProfile = apps.get_model('investors', 'InvestorProfile')

    def process_model(Model):
        print(f"\nProcessing model: {Model.__name__}")
        profiles_to_update = Model.objects.exclude(logo__isnull=True).exclude(logo='').exclude(logo__startswith='logos/')

        for profile in profiles_to_update:
            old_name = profile.logo.name
            old_name_cleaned = old_name.replace('media/', '', 1)

            if not default_storage.exists(old_name_cleaned):
                print(f"  - File not found in storage, skipping: {old_name_cleaned}")
                continue

            try:
                ext = os.path.splitext(old_name)[1].lower() or '.png'
                new_name = os.path.join('logos', f"{uuid.uuid4()}{ext}")

                with default_storage.open(old_name_cleaned, 'rb') as old_file:
                    content = old_file.read()

                default_storage.save(new_name, ContentFile(content))

                profile.logo.name = new_name
                profile.save(update_fields=['logo'])

                default_storage.delete(old_name_cleaned)

                print(f"  + Safely moved: {old_name_cleaned} -> {new_name}")

            except Exception as e:
                print(f"  ! Error processing {old_name}: {e}")

    process_model(StartupProfile)
    process_model(InvestorProfile)


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_alter_startupprofile_logo'),
        ('investors', '0003_alter_investorprofile_logo'),
    ]

    operations = [
        migrations.RunPython(consolidate_and_fix_logo_paths, reverse_code=migrations.RunPython.noop),
    ]
