# Generated by Django 5.2.7 on 2025-10-22 17:25


from django.db import migrations
import os
import shutil
import uuid
from django.conf import settings

def fix_logo_paths(apps, schema_editor):
    """
    Переміщує логотипи, які не були переміщені попередньою міграцією.
    Не використовує імпорт з проєкту, генерує UUID для нових імен.
    """
    StartupProfile = apps.get_model('startups', 'StartupProfile')
    InvestorProfile = apps.get_model('investors', 'InvestorProfile')
    
    MEDIA_ROOT = settings.MEDIA_ROOT
    if not MEDIA_ROOT:
        print("Warning: MEDIA_ROOT is not set. Skipping file operations.")
        return

    def process_model(Model):
        print(f"\nProcessing model: {Model.__name__}")
        profiles_to_update = Model.objects.exclude(logo__isnull=True).exclude(logo='').exclude(logo__startswith='logos/')
        
        for profile in profiles_to_update:
            old_name = profile.logo.name
            old_name_cleaned = old_name.replace('media/', '', 1)
            old_path = os.path.join(MEDIA_ROOT, old_name_cleaned)

            if not os.path.exists(old_path):
                print(f"  - File not found, skipping: {old_path}")
                continue

            ext = os.path.splitext(old_name)[1].lower() or '.png'
            new_basename = f"{uuid.uuid4()}{ext}"
            new_name = os.path.join('logos', new_basename)
            new_path = os.path.join(MEDIA_ROOT, new_name)

            try:
                os.makedirs(os.path.dirname(new_path), exist_ok=True)
                shutil.move(old_path, new_path)
                profile.logo.name = new_name
                profile.save(update_fields=['logo'])
                print(f"  + Moved: {old_path} -> {new_path}")
            except Exception as e:
                print(f"  ! Error moving {old_path}: {e}")

    process_model(StartupProfile)
    process_model(InvestorProfile)


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_move_logos_to_uuid'),
        ('investors', '0003_alter_investorprofile_logo'), # Переконайтесь, що залежність правильна
    ]

    operations = [
        migrations.RunPython(fix_logo_paths, reverse_code=migrations.RunPython.noop),
    ]
