# Generated by Django 5.2.7 on 2025-11-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startupprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='draft_saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='published_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
