# Generated by Django 5.2.7 on 2025-11-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startupprofile_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedStartup',
        ),
    ]
