# Generated by Django 5.2.7 on 2025-11-11 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('startups', '0006_startupprofile_draft_saved_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedStartup',
        ),
    ]
