# Generated by Django 5.2.7 on 2025-11-16 09:50

import django_mongodb_backend.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                (
                    'id',
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'conversation_id',
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    'participants',
                    django_mongodb_backend.fields.ArrayField(
                        base_field=models.UUIDField(), max_size=2
                    ),
                ),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'indexes': [
                    models.Index(
                        fields=['participants', 'last_message_at'],
                        name='conversatio_partici_a29dba_idx',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('conversation_id', models.UUIDField(editable=False)),
                ('sender_id', models.UUIDField(editable=False)),
                ('body', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('sent', 'Sent'),
                            ('delivered', 'Delivered'),
                            ('read', 'Read'),
                        ],
                        default='sent',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'indexes': [
                    models.Index(
                        fields=['conversation_id', 'created_at'],
                        name='messages_convers_3ebb41_idx',
                    )
                ],
            },
        ),
    ]
