# Generated by Django 5.2.7 on 2025-11-14 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_project_allow_overfunding_project_funded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_opt_in', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('expressed', 'Expressed'),
                            ('contacted', 'Contacted'),
                            ('ignored', 'Ignored'),
                        ],
                        default='expressed',
                        max_length=32,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'investor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expressed_interests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expressed_interests',
                        to='projects.project',
                    ),
                ),
            ],
        ),
    ]
