# Generated by Django 5.2.5 on 2025-10-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('investment_range_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_range_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_industries', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('region', models.IntegerField(choices=[(0, 'Cherkasy'), (1, 'Chernihiv'), (2, 'Chernivtsi'), (3, 'Dnipropetrovsk'), (4, 'Donetsk'), (5, 'Ivano-Frankivsk'), (6, 'Kherson'), (7, 'Kharkiv'), (8, 'Kyiv'), (9, 'Kirovohrad'), (10, 'Lviv'), (11, 'Mykolaiv'), (12, 'Odesa'), (13, 'Poltava'), (14, 'Rivne'), (15, 'Sumy'), (16, 'Ternopil'), (17, 'Vinnytsia'), (18, 'Volyn'), (19, 'Zaporizhzhia'), (20, 'Zhytomyr'), (21, 'Zakarpattia'), (22, 'Zaporizhzhia'), (23, 'Luhansk')], default=8)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='media/Investor_logos/')),
                ('partners_brands', models.TextField()),
                ('audit_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
            },
        ),
    ]
