# Generated by Django 5.2.7 on 2025-11-10 18:36

import uuid

import phonenumber_field.modelfields
from django.db import migrations, models

import apps.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('committed', 'committed'),
                            ('transferred', 'transferred'),
                            ('returned', 'returned'),
                            ('cancelled', 'cancelled'),
                        ],
                        default='committed',
                        max_length=50,
                    ),
                ),
                (
                    'amount_committed',
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    'amount_invested',
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('meta', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                (
                    'investment_range_min',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    'investment_range_max',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ('preferred_industries', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                (
                    'phone',
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region='UA'
                    ),
                ),
                ('country', models.CharField(max_length=100)),
                (
                    'region',
                    models.IntegerField(
                        choices=[
                            (0, 'Vinnytsia Region'),
                            (1, 'Volyn Region'),
                            (2, 'Luhansk Region'),
                            (3, 'Dnipropetrovsk Region'),
                            (4, 'Donetsk Region'),
                            (5, 'Zhytomyr Region'),
                            (6, 'Zakarpattia Region'),
                            (7, 'Zaporizhzhia Region'),
                            (8, 'Ivano-Frankivsk Region'),
                            (9, 'Kyiv City'),
                            (10, 'Kyiv Region'),
                            (11, 'Kirovohrad Region'),
                            (12, 'Sevastopol City'),
                            (13, 'Autonomous Republic of Crimea'),
                            (14, 'Lviv Region'),
                            (15, 'Mykolaiv Region'),
                            (16, 'Odesa Region'),
                            (17, 'Poltava Region'),
                            (18, 'Rivne Region'),
                            (19, 'Sumy Region'),
                            (20, 'Ternopil Region'),
                            (21, 'Kharkiv Region'),
                            (22, 'Kherson Region'),
                            (23, 'Khmelnytskyi Region'),
                            (24, 'Cherkasy Region'),
                            (25, 'Chernihiv Region'),
                            (26, 'Chernivtsi Region'),
                        ],
                        default=8,
                    ),
                ),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                (
                    'logo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.utils.logo_upload_to,
                    ),
                ),
                ('partners_brands', models.TextField(blank=True, default='')),
                ('audit_status', models.CharField(default='Pending', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_id', models.UUIDField(blank=True, null=True)),
                ('draft_saved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('computed_at', models.DateTimeField()),
                ('projects_count', models.IntegerField()),
                (
                    'total_committed',
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    'total_invested',
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ('summary', models.JSONField()),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'target_type',
                    models.CharField(
                        choices=[('startup', 'startup'), ('project', 'project')],
                        max_length=32,
                    ),
                ),
                ('target_id', models.UUIDField()),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('manual', 'manual'),
                            ('suggestion', 'suggestion'),
                            ('import', 'import'),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ('meta', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Trackings',
            },
        ),
    ]
