# Generated by Django 5.2.7 on 2025-11-10 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='investments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='investments',
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='investor_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='investor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='tracking',
            name='investor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tracking',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('investor', 'computed_at')},
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(
                fields=['investor'], name='investors_t_investo_ed1b09_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(
                fields=['target_type', 'target_id'],
                name='investors_t_target__62286b_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='tracking',
            unique_together={('investor', 'target_type', 'target_id')},
        ),
    ]
