# Generated by Django 5.2.7 on 2025-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='region',
            field=models.IntegerField(
                choices=[
                    (0, 'Vinnytsia Region'),
                    (1, 'Volyn Region'),
                    (2, 'Luhansk Region'),
                    (3, 'Dnipropetrovsk Region'),
                    (4, 'Donetsk Region'),
                    (5, 'Zhytomyr Region'),
                    (6, 'Zakarpattia Region'),
                    (7, 'Zaporizhzhia Region'),
                    (8, 'Ivano-Frankivsk Region'),
                    (9, 'Kyiv City'),
                    (10, 'Kyiv Region'),
                    (11, 'Kirovohrad Region'),
                    (12, 'Sevastopol City'),
                    (13, 'Autonomous Republic of Crimea'),
                    (14, 'Lviv Region'),
                    (15, 'Mykolaiv Region'),
                    (16, 'Odesa Region'),
                    (17, 'Poltava Region'),
                    (18, 'Rivne Region'),
                    (19, 'Sumy Region'),
                    (20, 'Ternopil Region'),
                    (21, 'Kharkiv Region'),
                    (22, 'Kherson Region'),
                    (23, 'Khmelnytskyi Region'),
                    (24, 'Cherkasy Region'),
                    (25, 'Chernihiv Region'),
                    (26, 'Chernivtsi Region'),
                ],
                default=8,
            ),
        ),
    ]
