# Generated by Django 5.2.7 on 2025-10-28 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_initial'),
        ('projects', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('committed', 'committed'), ('transferred', 'transferred'), ('returned', 'returned'), ('cancelled', 'cancelled')], default='committed', max_length=50)),
                ('amount_committed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField()),
                ('projects_count', models.IntegerField()),
                ('total_committed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=18)),
                ('summary', models.JSONField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'unique_together': {('investor', 'computed_at')},
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('startup', 'startup'), ('project', 'project')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('suggestion', 'suggestion'), ('import', 'import')], max_length=32, null=True)),
                ('meta', models.JSONField(null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['investor'], name='investors_t_investo_ed1b09_idx'), models.Index(fields=['target_type', 'target_id'], name='investors_t_target__62286b_idx')],
                'unique_together': {('investor', 'target_type', 'target_id')},
            },
        ),
    ]
