# Generated by Django 5.2.7 on 2025-10-22 13:43

from django.db import migrations, models

from apps.common.utils import logo_upload_to


class Migration(migrations.Migration):
    dependencies = [
        ('investors', '0004_investment_portfoliosnapshot_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=logo_upload_to),
        ),
    ]
