# Generated by Django 5.2.7 on 2025-11-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('investors', '0006_alter_investorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='draft_saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='published_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='investment_range_max',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='investment_range_min',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='partners_brands',
            field=models.TextField(blank=True, default=''),
        ),
    ]
