# Generated by Django 5.2.7 on 2025-11-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('investors', '0006_alter_investorprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('target_id', models.UUIDField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                (
                    'investor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saved_items',
                        to='investors.investorprofile',
                    ),
                ),
                (
                    'target_type',
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                ('app_label', 'startups'), ('model', 'startupprofile')
                            ),
                            models.Q(('app_label', 'projects'), ('model', 'project')),
                            _connector='OR',
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Saved Items',
                'verbose_name_plural': 'Saved Items',
                'unique_together': {('investor', 'target_type', 'target_id')},
            },
        ),
    ]
